### ISSUE TITLE
Can't test event key

### ISSUE THREAD

**Issue by lewispb** [cookpad/streamy#44]
The [RSpec helper](https://github.com/cookpad/streamy/blob/master/lib/streamy/helpers/rspec_helper.rb) doesn't let us test if the key is correct.

What do we think about extending `expect_published_event` to support also testing the `key` argument?

**Comment by balvig** [comment]
Sounds good! It was left out since `key` was basically randomly generated, so didn’t seem useful to make assertions on it 👍

**Comment by lewispb** [comment]
Closed via https://github.com/cookpad/streamy/pull/45
