### ISSUE TITLE
Change log level based on environment

### ISSUE THREAD

**Issue by sebasoga** [cookpad/streamy#53]
When uploading the locale file to OneSky I noticed got this unexpected output:
```rb
$ bin/rails onesky:upload
Uploading en.yml
Done!
2018-06-27 18:50:12 - Initiating graceful shutdown of Kafka Producers 🤞
2018-06-27 18:50:12 - Kafka producers shutdown successfully👌
```

I get that we want to make sure all events are sent when shutting down Rails, but this is just noise when running any rails command on `development`.

**Comment by lewispb** [comment]
We've solved this by allowing Streamy to be configured with it's own log file.

**Comment by sebasoga** [comment]
:+1:
