### ISSUE TITLE
CircleCI not running on forks

### ISSUE THREAD

**Issue by ChrisBr** [cookpad/streamy#76]
PR https://github.com/cookpad/streamy/pull/74 was created from my fork on streamy and as you can see, CircleCI did not run there.

It seems like it is needed to enable it first, see https://circleci.com/docs/2.0/oss/#build-pull-requests-from-forked-repositories

As Streamy is a public open source project, I think we should enable this.

cc @balvig

**Comment by balvig** [comment]
![Screen Shot 2019-04-18 at 9 29 38](https://user-images.githubusercontent.com/104138/56329001-808d4a80-61bc-11e9-8b8b-0963395cb252.png)

Done! Thanks @ChrisBr 👍
