### ISSUE TITLE
Double check `batched` implementation 

### ISSUE THREAD

**Issue by balvig** [cookpad/streamy#77]
I’m trying to understand how our implementation of `batched` messages works, I can see we have this:

https://github.com/cookpad/streamy/blob/da57b1da164c011e57078e7140c8879caed9f6ce/lib/streamy/message_buses/kafka_message_bus.rb#L22-L27

and further up we call `produce`: 

https://github.com/cookpad/streamy/blob/da57b1da164c011e57078e7140c8879caed9f6ce/lib/streamy/message_buses/kafka_message_bus.rb#L18

since we rely on the same `max_buffer_size` configuration as `ruby-kafka` itself, it seems an exception would be raised _before_ we get to the `batched` logic, since there the check resides in the `produce` method:

https://github.com/zendesk/ruby-kafka/blob/93c45a8c531e8b447f1cd9127c8bc6ce8070c0e6/lib/kafka/producer.rb#L199-L202

Am I missing something…? Would be great if you could shed some light! :bow:

**Comment by errm** [comment]
👀 yes this does seem to be a bug ... Perhaps I can check it today!
