### ISSUE TITLE
Possible issue with Avro::Messaging setup

### ISSUE THREAD

**Issue by lewispb** [cookpad/streamy#81]
I think there’s a problem with the way we’ve set up Avro::Messaging. It seems like every single event being published is causing us to query the schema registry. That means the schema registry is dealing with a fair bit of traffic. We should only need to query the schema registry when we boot the app because that’s the only time the schema can change

https://github.com/cookpad/streamy/blob/master/lib/streamy/avro_event.rb#L15
Possible fix would be something like `Streamy.avro_messaging = AvroTurf::Messaging.new(..)` on app boot.

**Comment by dannyd4315** [comment]
AvroTurf should be caching the schema when it is posted for the first time to the schema registry. Looking into.

**Comment by lewispb** [comment]
Thanks Danny!
